### PR TITLE
Update to InvMenu v4.1.1

### PR DESCRIPTION
**Pull request by AIPTU**
It's more about how outdated the user's php binaries are (support for php-ds for the stable version was dropped a week ago: https://github.com/pmmp/php-build-scripts/commit/855d00960ebe53fa5c0f71d6cd9b6588c51731cc so update InvMenu it can be a shortcut and fix name of Paroxity

### What does the PR change?
Does your Pull Request:
- resolve a bug? Yes, 
- #96 
- InvMenu https://github.com/Muqsit/InvMenu/commit/af247cf4b5d43b72c5a3fff74d13898bcf118cb1 fixed about php-ds and it's Paroxity without Team 

### Testing Environment

* PocketMine-MP: 3.21.1
* PHP: 7.4.21

### CODE REVIEW

**Comment by AIPTU** [comment]
@Aericio can you review this?

**Comment by Aericio** [comment]
i highly doubt this PR was tested.

**Comment by AIPTU** [comment]
Already tested.

**Comment by Aericio** [comment]
please resolve issues with phpstan.

**Comment by AIPTU** [comment]
Review again @Aericio

**Comment by TwistedAsylumMC** [comment]
Have you actually tested this time?

**Comment by AIPTU** [comment]
I've just tested this and it's working fine

**Comment by TwistedAsylumMC** [comment]
@AIPTU Record a video of you testing it, just from looking at the code it is clear it will not work

**Comment by AIPTU** [comment]
[Video](https://drive.google.com/file/d/1vPZVmq6Q3NJHqRxtW1hS8HGmrB-MCNrp/view?usp=drivesdk)

**Comment by Aericio** [comment]
Found a bug.

First time you use the key on the crate, the roulette menu will show up as normal.
Second time you use the key on the crate, the roulette menu no longer shows up, but you still get the reward.

Same thing for crate reward preview.

I can't even open my inventory after opening a crate, until I relog.

https://user-images.githubusercontent.com/16523741/128592727-d637795d-961c-4bbf-b828-bdd27c76b27a.mp4

**Comment by IcyEndymion004** [comment]
bruhh INVMENU IS GAY

**Comment by AIPTU** [comment]
> Found a bug.
> 
> First time you use the key on the crate, the roulette menu will show up as normal.
> Second time you use the key on the crate, the roulette menu no longer shows up, but you still get the reward.
> 
> Same thing for crate reward preview.
> 
> I can't even open my inventory after opening a crate, until I relog.
> 
>  2021-08-06_21-33-15.mp4

If using the InvCrashFix plugin it will fix this issue

**Pull request merged**
